Update changelog
mongodb-labs/pymongoexplain pull request #51
Opened 2022-01-06 23:43 UTC by juliusgeo

2022-01-06 23:51 UTC, blink1073 approved these changes
Thanks!

2022-01-07 00:08 UTC, ShaneHarvey requested changes

2022-01-07 00:08 UTC, ShaneHarvey commented on changelog.rst
> +- Added ability to explain command options
Can you rephrase this? Best would be to mention the feature or new parameter name itself so that users can find it.

2022-01-07 19:09 UTC, ShaneHarvey approved these changes

2022-01-07 20:28 UTC, merged